### ISSUE TITLE
Possibly new flaky test

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#705]
I've been seeing a new intermittent error creeping on the CI:
 - https://github.com/FuelLabs/fuels-ts/actions/runs/3757050329/jobs/6383815414#step:9:212

Re-running the workflow will usually fix it.
 - https://github.com/FuelLabs/fuels-ts/actions/runs/3757050329/jobs/6384031622

```
Summary of all failing tests
FAIL packages/fuel-gauge/src/call-test-contract.test.ts (8.925 s)
  ● CallTestContract › can call a contract with u64 (0)

    Invalid Transaction status

      183 |       }
      184 |       default: {
    > 185 |         throw new Error('Invalid Transaction status');
          |               ^
      186 |       }
      187 |     }
      188 |   }

      at TransactionResponse.waitForResult (packages/providers/src/transaction-response/transaction-response.ts:185:15)
          at runMicrotasks (<anonymous>)
      at async Function.build (packages/contract/src/contracts/functions/invocation-results.ts:106:22)
      at async /home/runner/work/fuels-ts/fuels-ts/packages/fuel-gauge/src/call-test-contract.test.ts:24:23


Test Suites: 1 failed, 1 skipped, 93 passed, 94 of 95 total
Tests:       1 failed, 7 skipped, 669 passed, 677 total
Snapshots:   32 passed, 32 total
Time:        184.816 s
Ran all test suites.
 ELIFECYCLE  Test failed. See above for more details.

```

**Comment by arboleya** [comment]
This <sup>_`"status": null`_</sup> is what I get when this test fails locally:


```ts
Invalid Transaction status: {
      "id": "0x696e716417ef73e74b86eebf22adc4caf82e5b821f284c6fbae29622227b3fa6",
      "rawPayload": "0x000000000000000000000000000000000000000005f5e10000000000000000000000000000000d2c00000000000002d0000000000000000200000000000000020000000000000001000000000000000000000000000000000000000000000000000000000000000090000004470000000000000000000cd45dfcc00110fff3001a5c5000910005b861440006724002d0164114005b40100d360000006158000c61440001504175305f5d10a6504175305d4570a6504171385f5d1027504171385d417027134100007340001a9000001f1a445000910000085d43f0005f4500009000002b504171385d4170271341004073400024900000291a445000910000085d43f0015f4500009000002b360000001a44000050417528504175286041100850457528504170085041700860411008504170085d4100001341000073400037900000396144000c9000003b360000001a440000504174305f5d1086504174305d4570865d43f00210450440504174485f5d108961440001504175405f5d10a8504175405d4570a8504171405f5d1028504171405d417028134100007340004f900000541a445000910000085d43f0005f45000090000060504171405d41702813410040734000599000005e1a445000910000085d43f0015f45000090000060360000001a44000050417538504175386041100850457538504170005041700060411008504170005d410000134100007340006c9000006e6144000690000078504170005d410000134100407340007390000076360000001a44000090000078360000001a4400005d43f00220451400504173805f5d1070504174485d497089504173805d4170701a445000910000105f4520005f450001504175a8504175a8604110105d47f00326440000504470015041726050417260604110a026000000504070011a445000910000105f4500005f440001504174785041747860411010504173505f5c006a5d47f0025d43f00412451400504173005f5d1060504173505d45706a504173005d41706016411400734000a4900000b150496000504173505d41706a5545009010452440504170785041707860411090504170785d41000013410040734001249000031f504972601a445000910000a050411000604120a05041748850417488604110a026000000504070011a445000910000105f4500005f44000150417198504171986041101050517198505574885d454001504174085f5d10815d4540015d43f00310450440504173c85f5d10795d4140005d4d4001504573c85d457079154914c0734800d3900000e12644000050487001504573a85f5d207515453000734400da900000de504573a85d457075284504c0900000de504173a85d417075900000e15f510000504173c85d4170795f5100015d454000504174085d417081104504405d43f0032845540050557198505174785d41400113410000734000f1900000f35d4150019000011c5d455001504174105f5d10825d4550015d41400110450440504173d05f5d107a5d4150005d4d5001504573d05d45707a154914c073480102900001102644000050487001504573b05f5d207615453000734401099000010d504573b05d457076284504c09000010d504173b05d417076900001105f550000504173d05d41707a5f5500015d4940005d455000504174105d417082104504405d414001284524005d417082504171985d450000504171985d41000125450000504574885d43f003254500005041707850450008504171a8504171a860411088504171a850450028504171085041710860411018504171085d41000013410000734001339000013f504171085d450002504175485f5d10a9504175485d4970a91a445000910000185d43f0005f4500005f4520029000017b504171085d41000013410040734001449000016050417108504100085d450000504173e85f5d107d50417108504100085d450001504173785f5d106f504175a85d450000504173e85d41707d10450440504173785d41706f1a485000910000105f4910005f4900011a445000910000185d43f0015f45000050411008604120109000017b50417108504100085d450000504173f05f5d107e50417108504100085d450001504173905f5d1072504175a85d450000504173f05d41707e10450440504173905d4170721a485000910000105f4910005f4900011a445000910000185d43f0015f4500005041100860412010504173085041730860411018504171a850550000504171a85d51000450457308504171a8504d0040504170105041701060411018504170105d410000134100007340018d90000194504170105d450002504175505f5d10aa504175505d4570aa900001a8504170105d4100001341004073400199900001a150417010504100085d450000504174385f5d1087504174385d457087900001a850417010504100085d450000504174505f5d108a504174505d45708a504173205f5d1064504173205d4970641a4450009100003050411000604150205f4540045f45200550417230504172306041103050453000504170285041702860411010504170285d41000013410040734001be900001c5504170285d450001504171485f5d1029504171485d457029900001cd504170285d41000013410000734001ca900001cc1a440000900001cd1a440000504171505f5d102a50453010504170385041703860411028504170385d41000013410040734001d8900001df504170385045000850417358504173586041102050497358900001f1504170385d41000013410000734001e4900001eb1a485000910000205d47f00a104513005041200060411020900001f11a485000910000205d47f00a10451300504120006041102050417158504171586041202050453038504170605041706060411010504170605d41000013410040734001fd90000204504170605d450001504173405f5d1068504173405d4570689000020c504170605d41000013410000734002099000020b1a44a0009000020c1a44a000504173485f5d1069504d7230504171505d49702a50457158504173485d4170692d4d24501a44e000504170705f5d100e504170705d41700e134100007340021d900002281a44d000504175785f5d10af504175785d4570af1a485000910000185d43f0005f4900005f4910029000023d504170705d45700e504173885f5d10711a44d000504174585f5d108b504174585d49708b504173885d4170711a445000910000105f4520005f4500011a485000910000185d43f0015f490000504120086041101050417460504174606041201850457460504171205041712060411018504171205d410000134100007340024990000255504171205d450002504175a05f5d10b4504175a05d4970b41a445000910000185d43f0005f4500005f45200290000309504171205d410000134100407340025a900002b250417120504100085d450000504174285f5d108550417120504100085d450001504173985f5d1073504174285d497085504173985d4170731a445000910000105f4520005f45000150417178504171786041101050557478505171785d4140011341000073400275900002775d455001900002a15d455001504174185f5d10835d4550015d41400110450440504173d85f5d107b5d4150005d4d5001504573d85d45707b154914c073480286900002942644000050487001504573b85f5d2077154530007344028d90000291504573b85d457077284504c090000291504173b85d417077900002945f550000504173d85d41707b5f5500015d4940005d455000504174185d417083104504405d41400128452400504174185d457083504173f85f5d107f504173f85d45707f504173985d4170731a485000910000105f4910005f4900011a445000910000185d43f0015f45000050411008604120109000030950417120504100085d450000504174405f5d108850417120504100085d450001504173a05f5d1074504174405d497088504173a05d4170741a445000910000105f4520005f45000150417188504171886041101050557478505171885d41400113410000734002cd900002cf5d455001900002f95d455001504174205f5d10845d4550015d41400110450440504173e05f5d107c5d4150005d4d5001504573e05d45707c154914c0734802de900002ec2644000050487001504573c05f5d207815453000734402e5900002e9504573c05d457078284504c0900002e9504173c05d417078900002ec5f550000504173e05d41707c5f5500015d4940005d455000504174205d417084104504405d41400128452400504174205d457084504174005f5d1080504174005d457080504173a05d4170741a485000910000105f4910005f4900011a445000910000185d43f0015f4500005041100860412010504173285041732860411018504973281a445000910000205d43f0015f450000504110086041201850417558504175586041102050457260504173505d41706a5549002010491480504575585d43f009284914009000032e504175801a445000910000205d43f0005f450000504175806041102050457260504173505d41706a5549002010491480504575805d43f0092849140050417350504173505d41706a104014005f5d006a9000009d470000000000000000000000000000000000000100000000000002d000000000000000a00000000000000090000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000cfc00000000000000000000000160773d353f4752b0dcbfcfe277a2b56d2f094632c929846609021ebe2f823be700000000cb3307c8000000000000000000000000000000000000000000000538000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000160773d353f4752b0dcbfcfe277a2b56d2f094632c929846609021ebe2f823be700000000cb3307c8000000000000000000000000000000000000000000000538000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060773d353f4752b0dcbfcfe277a2b56d2f094632c929846609021ebe2f823be700000000000000009233e7055e7a2745b0c99c563b34c65970bd813d3f3e56c6e9932ac93b28f28500000000000000020b55e1671bd0d3cea34b4bee1a42a09ac4511ae36eb362dd7d6adebecb68287300000000004c4b400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030b55e1671bd0d3cea34b4bee1a42a09ac4511ae36eb362dd7d6adebecb682873000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040631587cf9956ec601b89501de4ffff2110e80133f5afd42113046c9449f3fc0c3d621ad9c2d082616492ddfc4f24081dd6fdd1810d23754dfec587a2df4e5e20",
      "gasPrice": "0",
      "status": null,
      "receipts": [
        {
          "data": null,
          "rawPayload": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000060773d353f4752b0dcbfcfe277a2b56d2f094632c929846609021ebe2f823be7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005f56cf300000000cb3307c8000000000000053800000000000043400000000000004340"
        },
        {
          "data": null,
          "rawPayload": "0x000000000000000560773d353f4752b0dcbfcfe277a2b56d2f094632c929846609021ebe2f823be70000000000000538000000000000000100000000000000000000000000000000000000000000456c0000000000004340"
        },
        {
          "data": null,
          "rawPayload": "0x000000000000000160773d353f4752b0dcbfcfe277a2b56d2f094632c929846609021ebe2f823be7000000000000053900000000000045740000000000004340"
        },
        {
          "data": null,
          "rawPayload": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000060773d353f4752b0dcbfcfe277a2b56d2f094632c929846609021ebe2f823be7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005f4fd3d00000000cb3307c8000000000000053800000000000043f800000000000043f8"
        },
        {
          "data": null,
          "rawPayload": "0x000000000000000560773d353f4752b0dcbfcfe277a2b56d2f094632c929846609021ebe2f823be70000000000000538000000000000000100000000000000000000000000000000000000000000462400000000000043f8"
        },
        {
          "data": null,
          "rawPayload": "0x000000000000000160773d353f4752b0dcbfcfe277a2b56d2f094632c929846609021ebe2f823be70000000000000539000000000000462c00000000000043f8"
        },
        {
          "data": "0x00000000000000010000000000000000000000000000000000000000000005390000000000000001000000000000000000000000000000000000000000000539000000000000000000000000000030b80000000000003a9800000000000041a000000000000000000000000003ffff5f00000000000000000000000005f4f33d0000000000000000000000000000000000000000000028680000000000000539",
          "rawPayload": "0x000000000000000200000000000000000000000000000000000000000000000000000000000000000000000003fffec000000000000000a001f6981bde4c805442d5ad09f3104871179b8a947692a470540b631fe1f7334800000000000000a000000000000000010000000000000000000000000000000000000000000005390000000000000001000000000000000000000000000000000000000000000539000000000000000000000000000030b80000000000003a9800000000000041a000000000000000000000000003ffff5f00000000000000000000000005f4f33d00000000000000000000000000000000000000000000286800000000000005390000000000002ce80000000000002868"
        },
        {
          "data": null,
          "rawPayload": "0x0000000000000009000000000000000000000000000177b5000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        }
      ]
    }
```

**Comment by arboleya** [comment]
All the links I posted are for the CI action, which doesn't run things twice AFAIK. Right?

Even if running things locally, it should ideally never happen (if possible).

One case that comes to mind is when we are working in `test --watch` mode — if that makes sense.

Could this be solved with a global setup/teardown script?

**Comment by arboleya** [comment]
It happened again on [this PR](https://github.com/FuelLabs/fuels-ts/pull/695), link below:
 - https://github.com/FuelLabs/fuels-ts/actions/runs/3840226031/jobs/6539017500

I didn't re-run this one to keep the failed status intact.

**Comment by Dhaiwat10** [comment]
@arboleya I re-ran it before seeing your comment, apologies. It failed again, though. So thankfully we still have that.

**Comment by Dhaiwat10** [comment]
Happened again on #717

**Comment by arboleya** [comment]
@Dhaiwat10 On, no worries — the re-run also didn't fix it.

**Comment by arboleya** [comment]
This is another flaky test that is becoming more prevalent:
 - https://github.com/FuelLabs/fuels-ts/actions/runs/4323014226/jobs/7546110568#step:8:443

```
Summary of all failing tests
FAIL packages/fuel-gauge/src/generic-types-contract.test.ts
  ● GenericTypesContract › should call complex contract function with generic type

    expect(received).rejects.toThrow(expected)

    Expected pattern: /gasLimit\(10\) is lower than the required/
    Received message: "output already exists: {\"response\":{\"data\":null,\"errors\":[{\"message\":\"output already exists\",\"locations\":[{\"line\":2,\"column\":3}],\"path\":[\"dryRun\"]}],\"status\":200,\"headers\":{}},\"request\":{\"query\":\"mutation dryRun($encodedTransaction: HexString!, $utxoValidation: Boolean) {\\n  dryRun(tx: $encodedTransaction, utxoValidation: $utxoValidation) {\\n    ...receiptFragment\\n  }\\n}\\n\\nfragment receiptFragment on Receipt {\\n  data\\n  rawPayload\\n}\",\"variables\":{\"encodedTransaction\":\"0x00000000000000000000000000000190000000000000000a0000000000000000000000000000005000000000000000080000000000000001000000000000000100000000000000010000000000000000000000000000000000000000000000000000000000000000900000044700000000000000000000385dfcc00110fff3006148000c5d4920005d47f002104513005d43f001340004503348100024480000753820666f6f000000000000000000080000000000000038000000000000002a0000000000000000a1611dbafef44bfac4fa8d10b96cebeac4e46e599ffcf193e7a85fc15769cc5900000000000000011dcf6cd2b7bad331967e6a314a718ca4aaea8b08562c4b1ca7ee7a954ddbf2280000000000001388000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000031dcf6cd2b7bad331967e6a314a718ca4aaea8b08562c4b1ca7ee7a954ddbf22800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004093b1de4a1cd720391a1194cc3b0f44097eef8919a14dad7ae565b58cc1cdc851da811872aad20800eda5b45aa9e810c65ed274a7adf37f724e4abae237a7f9ad\",\"utxoValidation\":false}}}"

      76 |     expect(async () => {
      77 |       await scriptInstance.functions.main(foo).txParams({ gasLimit: 10, gasPrice: 400 }).call();
    > 78 |     }).rejects.toThrow(/gasLimit\(10\) is lower than the required/);
         |                ^
      79 |   });
      80 | });
      81 |

      at node_modules/.pnpm/graphql-request@5.0.0_graphql@16.6.0/node_modules/graphql-request/src/index.ts:497:11
      at step (node_modules/.pnpm/graphql-request@5.0.0_graphql@16.6.0/node_modules/graphql-request/dist/index.js:63:23)
      at Object.next (node_modules/.pnpm/graphql-request@5.0.0_graphql@16.6.0/node_modules/graphql-request/dist/index.js:44:53)
      at fulfilled (node_modules/.pnpm/graphql-request@5.0.0_graphql@16.6.0/node_modules/graphql-request/dist/index.js:35:58)
      at Object.toThrow (node_modules/.pnpm/expect@29.3.1/node_modules/expect/build/index.js:210:22)
      at Object.<anonymous> (packages/fuel-gauge/src/script-main-args.test.ts:78:16)
```
